### PR TITLE
implemented .extend() method

### LINKED ISSUE #9: Implement $.extend() functionality
Implement $.extend() functionality

### PR DESCRIPTION
**Pull request by ZauberNerd**
Closes #9

### CODE REVIEW

**Comment by garthenweb** [comment]
Do we need this? Object.assign should just do the job...

**Comment by ZauberNerd** [comment]
Hm. Until now we've only used ES5 features and the code runs in all browsers.
If we start using ES6 features, we'd need polyfills.
I'd say that, for the moment we should stick to ES5 and after we've implemented the still missing functionality we can start rewriting the code into modules and also introducing ES6 features.

**Comment by garthenweb** [comment]
The project in my eyes was never intended to run in "all" browser's nor to use es5 only. My goal was to write a library that's not bloated and easy to read/ understand. I also don't want to add polyfills into the library but of cause it would be cool if you could polyfills everything, if needed, without any build step.
Further I don't like to rebuild jquery. Of cause, jquery is kind of a foundation for the api but do we really need everything?
I would propose to not add extend until it is needed for this project. If we do need it I would use Object.assign anyway and add a polyfill for testing in phantomjs only (probably installed with bower).

**Comment by ZauberNerd** [comment]
Ok, closing this.

**Pull request closed without merging**
